name: Run all unit tests

on:
  pull_request:
    branches: [develop, main]

  push:
    branches: [develop]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Install pnpm
        run: npm install -g pnpm@latest-10
      - name: checkout branch
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
      - run: pnpm install --frozen-lockfile
      - run: pnpm run test
    